openapi: 3.0.0
info:
  title: Wallpaper Management API
  version: 1.0.0
  description: API for managing wallpapers and categories

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /admin/login:
    post:
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /admin/categories:
    post:
      summary: Add a new category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                category_image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Category created successfully
        '500':
          description: Internal server error

  /admin/categories/{id}:
    put:
      summary: Update a category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                category_image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Category updated successfully
        '500':
          description: Internal server error
    delete:
      summary: Delete a category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Category deleted successfully
        '404':
          description: Category not found
        '500':
          description: Internal server error

  /categories:
    get:
      summary: Get categories
      tags:
        - Categories
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          default: 1
        - name: limit
          in: query
          schema:
            type: integer
          default: 10
        - name: pagination
          in: query
          schema:
            type: string
            enum: [on, off]
      responses:
        '200':
          description: Categories retrieved successfully
        '500':
          description: Internal server error

  /add:
    post:
      summary: Upload a category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                category_image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Category uploaded successfully
        '500':
          description: Internal server error

  /home:
    get:
      summary: Get categories with wallpapers
      tags:
        - Categories
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          default: 1
        - name: limit
          in: query
          schema:
            type: integer
          default: 10
      responses:
        '200':
          description: Categories with wallpapers retrieved successfully
        '500':
          description: Internal server error

  /categories/{id}:
    get:
      summary: Get a category with wallpapers
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
          default: 1
        - name: limit
          in: query
          schema:
            type: integer
          default: 10
      responses:
        '200':
          description: Category with wallpapers retrieved successfully
        '500':
          description: Internal server error

  /admin/wallpaper/{id}:
    put:
      summary: Update a wallpaper
      tags:
        - Wallpapers
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Wallpaper updated successfully
        '500':
          description: Internal server error
    delete:
      summary: Delete a wallpaper
      tags:
        - Wallpapers
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Wallpaper deleted successfully
        '500':
          description: Internal server error

  /admin/wallpaper:
    post:
      summary: Add new wallpapers
      tags:
        - Wallpapers
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                category_name:
                  type: string
                category_image:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Wallpapers added successfully
        '500':
          description: Internal server error

  /admin/wallpapers:
    get:
      summary: Get all wallpapers
      tags:
        - Wallpapers
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          default: 1
        - name: limit
          in: query
          schema:
            type: integer
          default: 50
      responses:
        '200':
          description: Wallpapers retrieved successfully
        '500':
          description: Internal server error

  /wallpapers:
    get:
      summary: Get random wallpapers
      tags:
        - Wallpapers
      responses:
        '200':
          description: Wallpapers retrieved successfully
        '500':
          description: Internal server error

  /wallpapers:
    post:
      summary: Search wallpapers by category
      tags:
        - Wallpapers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
      responses:
        '200':
          description: Search results retrieved successfully
        '400':
          description: Category is required
        '500':
          description: Internal server error
